# Application Name
spring.application.name=jdm-expo-eureka-server

# Connect to Config Server on port 8888 to pull central configurations
spring.config.import=optional:configserver:http://localhost:8888

# Server Port
server.port=8761
