# Application Name
spring.application.name=jdm-expo-eureka-server

spring.config.import=configserver:
spring.cloud.config.uri=http://config.platform:8888

# Fetch centralized settings from Config Server
#spring.config.import=configserver:http://localhost:8888

# Server Port
server.port=8761
